language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "cd namedropper-py"
  - "pip install . --use-mirrors"
# not running coverage or building docs and mock is pre-installed, so dev reqs probably aren't needed
# - "pip install -r pip-dev-req.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests